linters-settings:
  funlen:
    lines: 110
    statements: 70
  gci:
    sections:
      - standard
      - default
      - localmodule
    custom-order: true
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  cyclop:
    skip-tests: true
    max-complexity: 15
  godot:
    capital: true
  goimports:
    local-prefixes: github.com/lzambarda/goflat
  govet:
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    disable:
      - fieldalignment
  lll:
    line-length: 140
  misspell:
    locale: UK
  tagliatelle:
    case:
      rules:
        json: snake
  unparam:
    check-exported: true

  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - errors.Join(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - status.Error(

  wsl:
    allow-cuddle-declarations: true

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - bodyclose
        - dupl # we usually duplicate code in tests
        - dupword
        - errcheck
        - errchkjson # we mostly dump file diffs, no biggie
        - funlen
        - gochecknoglobals
        - goconst # sometimes it is easier this way
        - gocritic
        - gosec # security check is not important in tests
        - govet
        - maintidx
        - revive
        - unparam
        - varnamelen
        - wrapcheck
    - path: testing
      linters:
        - errcheck
  fix: true
  exclude-use-default: false
  exclude-dirs:
    - model
    - tmp
    - bin
    - scripts

run:
  allow-parallel-runners: true
  tests: true
  build-tags:
    - integration

linters:
  enable-all: true
  disable:
    - exhaustruct # I want to use zero values... and sometime leave a field uninitialised, because it'll be later.
    - depguard # because I don't want to write a dedicated config file.
    - nonamedreturns # I don't fully agree with this
    - paralleltest # I don't agree with this level of nitpicking
