version: "2"
run:
  build-tags:
    - integration
  tests: true
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - nonamedreturns
    - paralleltest
    - noinlineerr # Seriously some people are purists
  settings:
    cyclop:
      max-complexity: 15
    funlen:
      lines: 110
      statements: 70
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    godot:
      capital: true
    govet:
      disable:
        - fieldalignment
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 140
    misspell:
      locale: UK
    tagliatelle:
      case:
        rules:
          json: snake
    unparam:
      check-exported: true
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - errors.Join(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - status.Error(
    wsl:
      allow-cuddle-declarations: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - bodyclose
          - dupl
          - dupword
          - errcheck
          - errchkjson
          - funlen
          - gochecknoglobals
          - goconst
          - gocritic
          - gosec
          - govet
          - maintidx
          - revive
          - unparam
          - varnamelen
          - wrapcheck
        path: _test\.go
      - linters:
          - errcheck
        path: testing
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - model
      - tmp
      - bin
      - scripts
      - third_party$
      - builtin$
      - examples$
issues:
  fix: true
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      custom-order: true
    goimports:
      local-prefixes:
        - github.com/lzambarda/goflat
  exclusions:
    generated: lax
    paths:
      - model
      - tmp
      - bin
      - scripts
      - third_party$
      - builtin$
      - examples$
